apiVersion: v2
name: foundry-vtt
description: Foundry Virtual Tabletop
type: application
icon: https://artifacthub.io/image/3e8ce5cf-7afe-4032-bae2-500b17e64b11@1x
version: 13.346.0
appVersion: "v13.346"
keywords:
  - vtt
  - virtualtabletop
  - foundryvtt
  - foundry
sources:
  - https://github.com/dynomite567/helm-charts/tree/main/foundry-vtt
maintainers:
  - name: dynomite567
    email: 17055345+dynomite567@users.noreply.github.com
