{{- $name := or .Values.immich.persistence.library.existingClaim .Values.immich.persistence.library.nfs.server | required ".Values.immich.persistence.library.existingClaim or .Values.immich.persistence.library.nfs.server is required." -}}

{{ if .Values.postgresql.enabled }}
  {{ if not .Values.useDeprecatedPostgresChart}}
    {{ fail "The postgres subchart is deprecated. Please see https://github.com/immich-app/immich-charts/issues/149 for more detail." }}
  {{ end }}
{{ end }}
