apiVersion: v2
name: librechat
description: A Helm chart for LibreChat
type: application
version: 1.8.10
appVersion: "v0.8.0-rc2"
home: https://www.librechat.ai
icon: https://raw.githubusercontent.com/danny-avila/LibreChat/refs/heads/main/client/public/assets/logo.svg

sources:
  - https://github.com/dynomite567/helm-charts/tree/main/charts/librechat
  - https://github.com/danny-avila/LibreChat

keywords:
  - librechat

maintainers:
  - name: dynomite567
    email: 17055345+dynomite567@users.noreply.github.com

dependencies:
  - name: mongodb
    version: "16.3.0"
    condition: mongodb.enabled
    repository: "https://charts.bitnami.com/bitnami"
  - name: meilisearch
    version: "0.11.0"
    condition: meilisearch.enabled
    repository: "https://meilisearch.github.io/meilisearch-kubernetes"
  - name: librechat-rag-api
    version: "0.5.2"
    condition: librechat-rag-api.enabled
    repository: file://../librechat-rag-api
