name: Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true
          CR_SKIP_EXISTING: true

      - name: Check for OCI Charts
        id: ocicheck
        run: |
          FILE=.cr-release-packages/
          if [ -d "$FILE" ]; then
            echo "oci_release=true" >> $GITHUB_OUTPUT
          else
            echo "oci_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container Registry
        if: ${{ steps.ocicheck.outputs.oci_release == 'true' }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push OCI Charts
        if: ${{ steps.ocicheck.outputs.oci_release == 'true' }}
        run: |
          files=$(find .cr-release-packages/ -type f -name "*.tgz")
          for pkg in $files; do
            echo "Pushing ${pkg} to ghcr.io/$owner"
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" oci://ghcr.io/${{ github.repository }}
          done
